"""added source field in DocumentChunk

Revision ID: ccd1c9b18d5c
Revises: befcfc96fcf6
Create Date: 2026-09-05 21:14:58.171637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd1c9b18d5c'
down_revision: Union[str, Sequence[str], None] = 'befcfc96fcf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'source')
    # ### end Alembic commands ###
